from __future__ import annotations

import argparse
from pathlib import Path

from .common import check_args, default_log_name, resolve_path, setup_log_file
from .io import default_jscc_decoder_c36, default_jscc_encoder_c36, default_save_dir
from .stage1 import train_stage1
from .stage2 import init_codebook_from_stage1
from .stage3 import train_stage3
from .stage4 import oracle_eval
from .stage5 import train_stage5
from .stage6 import train_stage6

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--stage", type=int, required=True, choices=[1, 2, 3, 4, 5, 6])
    p.add_argument("--data-dir", type=str, default="/workspace/yongjia/datasets/DIV2K")
    p.add_argument("--save-dir", type=str, default=default_save_dir())
    p.add_argument("--log-file", type=str, default="")
    p.add_argument("--init-ckpt", type=str, default="")
    p.add_argument("--init-jscc-encoder", type=str, default=default_jscc_encoder_c36())
    p.add_argument("--init-jscc-decoder", type=str, default=default_jscc_decoder_c36())
    p.add_argument("--snr-db", type=float, default=9.0)
    p.add_argument("--latent-ch", type=int, default=36)
    p.add_argument("--prefix-ch", type=int, default=16)
    p.add_argument("--latent-h", type=int, default=16)
    p.add_argument("--latent-w", type=int, default=16)
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--test-batch", type=int, default=1)
    p.add_argument("--num-workers", type=int, default=16)
    p.add_argument("--val-num-workers", type=int, default=8)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--decoder-lr", type=float, default=2e-5)
    p.add_argument("--car-lr", type=float, default=1e-4)
    p.add_argument("--val-every", type=int, default=5)
    p.add_argument("--latest-every", type=int, default=10)
    p.add_argument("--seed", type=int, default=20260605)
    p.add_argument("--cpu", action="store_true")

    p.add_argument("--lambda-prefix", type=float, default=1.0)
    p.add_argument("--lambda-full", type=float, default=0.5)
    p.add_argument("--lambda-nested", type=float, default=0.5)
    p.add_argument("--stage1-full-warm-epochs", type=int, default=30)
    p.add_argument("--stage1-warm-lambda-prefix", type=float, default=0.5)
    p.add_argument("--stage1-warm-lambda-full", type=float, default=1.0)
    p.add_argument("--lambda-prefix-stage3", type=float, default=0.02)
    p.add_argument("--lambda-nested-stage3", type=float, default=0.02)
    p.add_argument("--lambda-cont-stage3", type=float, default=0.05)
    p.add_argument("--lambda-tail-distill", type=float, default=0.02)
    p.add_argument("--lambda-usage", type=float, default=0.0005)
    p.add_argument("--lambda-gain-stage3", type=float, default=0.0)
    p.add_argument("--lambda-prefix-floor-stage3", type=float, default=0.0)
    p.add_argument("--stage3-gain-margin-db", type=float, default=0.2)
    p.add_argument("--stage3-prefix-floor-db", type=float, default=25.2)
    p.add_argument("--stage3-usage-tau", type=float, default=10.0)
    p.add_argument("--stage3-teacher-ckpt", type=str, default="")
    p.add_argument("--stage3-aux-start-epoch", type=int, default=50)
    p.add_argument("--stage3-aux-tail-gain-threshold", type=float, default=0.2)
    p.add_argument("--freeze-encoder-first", type=int, default=0)
    p.add_argument("--lambda-vq-start", type=float, default=1e-4)
    p.add_argument("--lambda-vq-end", type=float, default=5e-3)
    p.add_argument("--vq-ramp-epochs", type=int, default=40)
    p.add_argument("--vq-beta", type=float, default=0.25)
    p.add_argument("--vq-chunk-size", type=int, default=128)
    p.add_argument("--cvq-mode", type=str, default="single", choices=["single", "rvq", "rvq_per_channel", "patch", "fsq", "fsq_shared"])
    p.add_argument("--rvq-stages", type=int, default=2)
    p.add_argument("--patch-size", type=int, default=4)
    p.add_argument("--fsq-levels-a", type=int, default=16)
    p.add_argument("--fsq-levels-b", type=int, default=16)
    p.add_argument("--fsq-scale", type=float, default=3.0)
    p.add_argument("--k-a", type=int, default=512)
    p.add_argument("--k-b", type=int, default=256)
    p.add_argument("--min-init-vectors", type=int, default=1024)
    p.add_argument("--init-vectors-per-code", type=int, default=8)
    p.add_argument("--kmeans-iters", type=int, default=25)
    p.add_argument("--kmeans-chunk-size", type=int, default=1024)
    p.add_argument("--dead-code-restart-every", type=int, default=5)
    p.add_argument(
        "--dead-code-restart-until",
        type=int,
        default=-1,
        help="last Stage 3 epoch allowed to restart dead codes; -1 uses --freeze-encoder-first",
    )
    p.add_argument("--dead-code-restart-pool", type=int, default=4096)
    p.add_argument("--stage3-train-encoder", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--stage3-train-decoder", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--stage3-freeze-encoder-body", action="store_true")
    p.add_argument("--stage3-freeze-prefix-head", action="store_true")
    p.add_argument("--stage3-min-used-a", type=int, default=50)
    p.add_argument("--stage3-min-used-b", type=int, default=20)
    p.add_argument("--stage3-min-tail-gain-vq", type=float, default=0.1)
    p.add_argument("--stage3-min-tail-gain-car", type=float, default=0.0)
    p.add_argument("--stage3-min-tail-gain-cont", type=float, default=1.0)
    p.add_argument("--stage3-min-psnr-prefix", type=float, default=0.0)
    p.add_argument("--stage3-min-perplexity-a", type=float, default=28.0)
    p.add_argument("--stage3-min-perplexity-b", type=float, default=10.0)
    p.add_argument("--stage3-score", type=str, default="tail_gain_vq", choices=["tail_gain_vq", "psnr_vq", "gap_vq", "tail_gain_car", "psnr_car", "gap_car_to_vq_oracle"])
    p.add_argument("--stage3-car-mode", type=str, default="none", choices=["none", "a", "all"])
    p.add_argument("--stage3-init-car-ckpt", type=str, default="")
    p.add_argument("--stage3-car-start-epoch", type=int, default=1)
    p.add_argument("--lambda-stage3-car-rec", type=float, default=0.0)
    p.add_argument("--lambda-stage3-car-ce", type=float, default=0.0)
    p.add_argument("--lambda-stage3-car-value", type=float, default=0.0)
    p.add_argument("--lambda-stage3-car-ordinal", type=float, default=0.0)
    p.add_argument("--lambda-stage3-car-gain", type=float, default=0.0)
    p.add_argument("--lambda-stage3-car-predictable", type=float, default=0.0)
    p.add_argument("--stage3-car-gain-db", type=float, default=0.5)
    p.add_argument("--stage3-car-tail-scale", type=float, default=1.0)
    p.add_argument("--stage3-car-soft-tau", type=float, default=1.0)
    p.add_argument("--stage3-car-alpha-sweep", type=str, default="")
    p.add_argument("--stage3-car-conf-floor", type=float, default=0.0)
    p.add_argument("--stage3-car-conf-gamma", type=float, default=0.0)
    p.add_argument("--stage3-car-value-mode", type=str, default="posterior", choices=["posterior", "direct", "residual"])
    p.add_argument("--stage3-car-direct-residual-scale", type=float, default=1.0)
    p.add_argument("--stage3-car-predictable-target", type=str, default="tail", choices=["tail", "quant"])
    p.add_argument("--stage3-car-predictable-ramp-epochs", type=int, default=1)
    p.add_argument("--stage3-car-predictable-detach-car", action=argparse.BooleanOptionalAction, default=True)

    p.add_argument("--car-arch", type=str, default="auto", choices=["auto", "legacy", "swin", "factorized_swin"])
    p.add_argument("--car-dim", type=int, default=256)
    p.add_argument("--car-heads", type=int, default=8)
    p.add_argument("--car-layers", type=int, default=4)
    p.add_argument("--car-dropout", type=float, default=0.1)
    p.add_argument("--car-window-size", type=int, default=4)
    p.add_argument("--car-prefix-image-cond", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--car-prefix-image-scale-init", type=float, default=0.1)
    p.add_argument("--lambda-stage5-rec", type=float, default=0.0)
    p.add_argument("--lambda-stage5-prefix", type=float, default=0.0)
    p.add_argument("--lambda-stage5-gain-margin", type=float, default=0.0)
    p.add_argument("--stage5-gain-margin-db", type=float, default=0.5)
    p.add_argument("--lambda-stage5-value", type=float, default=0.0)
    p.add_argument("--lambda-stage5-ordinal", type=float, default=0.0)
    p.add_argument("--stage5-soft-tau", type=float, default=1.0)
    p.add_argument("--stage5-fsq-generate", type=str, default="mean", choices=["argmax", "mean"])
    p.add_argument("--stage5-min-tail-gain-car", type=float, default=0.0)
    p.add_argument("--stage5-fsq-strategy", type=str, default="joint", choices=["joint", "two_stage", "gated", "ordinal", "maskgit", "coarse_a", "coarse_a_residual", "posterior_gated_a", "posterior_softar_a", "posterior_softar_all"])
    p.add_argument("--stage5-two-stage-a-epochs", type=int, default=50)
    p.add_argument("--stage5-gate-threshold", type=float, default=0.55)
    p.add_argument("--stage5-gate-b-threshold", type=float, default=-1.0)
    p.add_argument("--stage5-gate-soft-temp", type=float, default=0.08)
    p.add_argument("--stage5-gate-sweep", type=str, default="-1,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9")
    p.add_argument("--stage5-tail-scale", type=float, default=1.0)
    p.add_argument("--stage5-alpha-sweep", type=str, default="")
    p.add_argument("--stage5-mc-samples", type=int, default=0)
    p.add_argument("--stage5-maskgit-iters", type=int, default=6)
    p.add_argument("--stage5-maskgit-mask-prob", type=float, default=0.6)
    p.add_argument("--stage5-fsq-coarse-levels", type=int, default=4)
    p.add_argument("--lambda-stage5-residual", type=float, default=1.0)
    p.add_argument("--lambda-stage5-gate-l1", type=float, default=0.0)
    p.add_argument("--stage5-residual-threshold", type=float, default=-1.0)
    p.add_argument("--stage5-coarse-gate-to-zero", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--stage5-init-car-ckpt", type=str, default="")
    p.add_argument("--stage5-train-encoder", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--stage5-freeze-encoder-body", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--stage5-train-prefix-head-only", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--stage5-train-cvq", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--stage5-cvq-lr", type=float, default=2e-6)
    p.add_argument("--lambda-stage5-vq", type=float, default=0.0)
    p.add_argument("--stage5-train-decoder", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--lambda-stage6-rec", type=float, default=100.0)
    p.add_argument("--stage6-soft-tau", type=float, default=1.0)
    p.add_argument("--with-lpips", action="store_true")
    return p.parse_args()

def main() -> None:
    args = parse_args()
    check_args(args)
    Path(resolve_path(args.save_dir)).mkdir(parents=True, exist_ok=True)
    if not args.log_file:
        args.log_file = str(Path(args.save_dir) / default_log_name(int(args.stage), float(args.snr_db), int(args.latent_ch)))
    setup_log_file(args.log_file)
    if int(args.stage) == 1:
        train_stage1(args)
    elif int(args.stage) == 2:
        init_codebook_from_stage1(args)
    elif int(args.stage) == 3:
        train_stage3(args)
    elif int(args.stage) == 4:
        oracle_eval(args)
    elif int(args.stage) == 5:
        train_stage5(args)
    elif int(args.stage) == 6:
        train_stage6(args)
    else:
        raise ValueError(args.stage)


if __name__ == "__main__":
    main()
