#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SAVE_DIR="${SAVE_DIR:-MY/checkpoints-cvq-fsq8x8-factorized-swin-v1}"
INIT_CKPT="${INIT_CKPT:-MY/checkpoints-cvq-fsq8x8-tailfocus-e2e-vq1e3/cvq_c36_snr9_stage3_best.pth}"
DATA_DIR="${DATA_DIR:-/workspace/yongjia/datasets/DIV2K}"
PY="${PY:-conda run -n cddm_ddnm python}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-2}"
STAGE5_EPOCHS="${STAGE5_EPOCHS:-120}"
K_A="${K_A:-8}"
K_B="${K_B:-8}"
FSQ_LEVELS_A="${FSQ_LEVELS_A:-$K_A}"
FSQ_LEVELS_B="${FSQ_LEVELS_B:-$K_B}"
BATCH_SIZE="${BATCH_SIZE:-8}"
TEST_BATCH="${TEST_BATCH:-1}"
NUM_WORKERS="${NUM_WORKERS:-16}"
VAL_NUM_WORKERS="${VAL_NUM_WORKERS:-8}"
VAL_EVERY="${VAL_EVERY:-5}"
LATEST_EVERY="${LATEST_EVERY:-10}"
SEED="${SEED:-20260608}"
LR="${LR:-1e-4}"
CAR_DIM="${CAR_DIM:-192}"
CAR_HEADS="${CAR_HEADS:-6}"
CAR_LAYERS="${CAR_LAYERS:-4}"
CAR_DROPOUT="${CAR_DROPOUT:-0.05}"
CAR_WINDOW_SIZE="${CAR_WINDOW_SIZE:-4}"
CAR_LR="${CAR_LR:-1e-4}"
DECODER_LR="${DECODER_LR:-2e-5}"
LAMBDA_STAGE5_REC="${LAMBDA_STAGE5_REC:-100}"
LAMBDA_STAGE5_PREFIX="${LAMBDA_STAGE5_PREFIX:-0}"
LAMBDA_STAGE5_GAIN_MARGIN="${LAMBDA_STAGE5_GAIN_MARGIN:-0}"
STAGE5_GAIN_MARGIN_DB="${STAGE5_GAIN_MARGIN_DB:-0.2}"
LAMBDA_STAGE5_VALUE="${LAMBDA_STAGE5_VALUE:-0.5}"
LAMBDA_STAGE5_ORDINAL="${LAMBDA_STAGE5_ORDINAL:-0.0}"
LAMBDA_STAGE5_VQ="${LAMBDA_STAGE5_VQ:-0.0}"
STAGE5_SOFT_TAU="${STAGE5_SOFT_TAU:-1.0}"
STAGE5_FSQ_GENERATE="${STAGE5_FSQ_GENERATE:-mean}"
STAGE5_MIN_TAIL_GAIN_CAR="${STAGE5_MIN_TAIL_GAIN_CAR:-0.0}"
STAGE5_FSQ_STRATEGY="${STAGE5_FSQ_STRATEGY:-joint}"
STAGE5_TWO_STAGE_A_EPOCHS="${STAGE5_TWO_STAGE_A_EPOCHS:-50}"
STAGE5_GATE_THRESHOLD="${STAGE5_GATE_THRESHOLD:-0.55}"
STAGE5_GATE_B_THRESHOLD="${STAGE5_GATE_B_THRESHOLD:--1.0}"
STAGE5_GATE_SOFT_TEMP="${STAGE5_GATE_SOFT_TEMP:-0.08}"
STAGE5_GATE_SWEEP="${STAGE5_GATE_SWEEP:--1,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9}"
STAGE5_TAIL_SCALE="${STAGE5_TAIL_SCALE:-1.0}"
STAGE5_ALPHA_SWEEP="${STAGE5_ALPHA_SWEEP:-}"
STAGE5_MC_SAMPLES="${STAGE5_MC_SAMPLES:-0}"
STAGE5_MASKGIT_ITERS="${STAGE5_MASKGIT_ITERS:-6}"
STAGE5_MASKGIT_MASK_PROB="${STAGE5_MASKGIT_MASK_PROB:-0.6}"
STAGE5_FSQ_COARSE_LEVELS="${STAGE5_FSQ_COARSE_LEVELS:-4}"
LAMBDA_STAGE5_RESIDUAL="${LAMBDA_STAGE5_RESIDUAL:-1.0}"
LAMBDA_STAGE5_GATE_L1="${LAMBDA_STAGE5_GATE_L1:-0.0}"
STAGE5_RESIDUAL_THRESHOLD="${STAGE5_RESIDUAL_THRESHOLD:-0.65}"
STAGE5_COARSE_GATE_TO_ZERO="${STAGE5_COARSE_GATE_TO_ZERO:-1}"
STAGE5_TRAIN_ENCODER="${STAGE5_TRAIN_ENCODER:-0}"
STAGE5_FREEZE_ENCODER_BODY="${STAGE5_FREEZE_ENCODER_BODY:-0}"
STAGE5_TRAIN_PREFIX_HEAD_ONLY="${STAGE5_TRAIN_PREFIX_HEAD_ONLY:-0}"
STAGE5_TRAIN_CVQ="${STAGE5_TRAIN_CVQ:-0}"
STAGE5_CVQ_LR="${STAGE5_CVQ_LR:-2e-6}"
STAGE5_TRAIN_DECODER="${STAGE5_TRAIN_DECODER:-0}"

export CUDA_VISIBLE_DEVICES
mkdir -p "$SAVE_DIR"

{
  echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
  echo "SAVE_DIR=$SAVE_DIR"
  echo "INIT_CKPT=$INIT_CKPT"
  echo "CVQ_MODE=fsq"
  echo "K_A=$K_A K_B=$K_B FSQ_LEVELS_A=$FSQ_LEVELS_A FSQ_LEVELS_B=$FSQ_LEVELS_B"
  echo "CAR_ARCH=factorized_swin"
  echo "CAR_DIM=$CAR_DIM CAR_HEADS=$CAR_HEADS CAR_LAYERS=$CAR_LAYERS CAR_WINDOW_SIZE=$CAR_WINDOW_SIZE"
  echo "STAGE5_FSQ_STRATEGY=$STAGE5_FSQ_STRATEGY"
  echo "STAGE5_FSQ_COARSE_LEVELS=$STAGE5_FSQ_COARSE_LEVELS STAGE5_RESIDUAL_THRESHOLD=$STAGE5_RESIDUAL_THRESHOLD STAGE5_COARSE_GATE_TO_ZERO=$STAGE5_COARSE_GATE_TO_ZERO"
  echo "LAMBDA_STAGE5_REC=$LAMBDA_STAGE5_REC LAMBDA_STAGE5_VALUE=$LAMBDA_STAGE5_VALUE LAMBDA_STAGE5_ORDINAL=$LAMBDA_STAGE5_ORDINAL LAMBDA_STAGE5_VQ=$LAMBDA_STAGE5_VQ"
  echo "LAMBDA_STAGE5_GAIN_MARGIN=$LAMBDA_STAGE5_GAIN_MARGIN STAGE5_GAIN_MARGIN_DB=$STAGE5_GAIN_MARGIN_DB"
  echo "STAGE5_SOFT_TAU=$STAGE5_SOFT_TAU STAGE5_FSQ_GENERATE=$STAGE5_FSQ_GENERATE"
  echo "STAGE5_GATE_THRESHOLD=$STAGE5_GATE_THRESHOLD STAGE5_GATE_B_THRESHOLD=$STAGE5_GATE_B_THRESHOLD"
  echo "STAGE5_TAIL_SCALE=$STAGE5_TAIL_SCALE STAGE5_ALPHA_SWEEP=$STAGE5_ALPHA_SWEEP STAGE5_MC_SAMPLES=$STAGE5_MC_SAMPLES"
  echo "STAGE5_MASKGIT_ITERS=$STAGE5_MASKGIT_ITERS STAGE5_MASKGIT_MASK_PROB=$STAGE5_MASKGIT_MASK_PROB"
  echo "STAGE5_TRAIN_ENCODER=$STAGE5_TRAIN_ENCODER STAGE5_FREEZE_ENCODER_BODY=$STAGE5_FREEZE_ENCODER_BODY STAGE5_TRAIN_PREFIX_HEAD_ONLY=$STAGE5_TRAIN_PREFIX_HEAD_ONLY LR=$LR"
  echo "STAGE5_TRAIN_CVQ=$STAGE5_TRAIN_CVQ STAGE5_CVQ_LR=$STAGE5_CVQ_LR"
  echo "STAGE5_TRAIN_DECODER=$STAGE5_TRAIN_DECODER DECODER_LR=$DECODER_LR"
  echo "STAGE5_MIN_TAIL_GAIN_CAR=$STAGE5_MIN_TAIL_GAIN_CAR"
  echo "started_at=$(date '+%Y-%m-%d %H:%M:%S')"
} > "$SAVE_DIR/launch.meta"

extra_args=()
if [[ "$STAGE5_COARSE_GATE_TO_ZERO" == "1" || "$STAGE5_COARSE_GATE_TO_ZERO" == "true" || "$STAGE5_COARSE_GATE_TO_ZERO" == "yes" ]]; then
  extra_args+=(--stage5-coarse-gate-to-zero)
fi
if [[ "$STAGE5_TRAIN_DECODER" == "1" || "$STAGE5_TRAIN_DECODER" == "true" || "$STAGE5_TRAIN_DECODER" == "yes" ]]; then
  extra_args+=(--stage5-train-decoder)
fi
if [[ "$STAGE5_TRAIN_ENCODER" == "1" || "$STAGE5_TRAIN_ENCODER" == "true" || "$STAGE5_TRAIN_ENCODER" == "yes" ]]; then
  extra_args+=(--stage5-train-encoder)
fi
if [[ "$STAGE5_FREEZE_ENCODER_BODY" == "1" || "$STAGE5_FREEZE_ENCODER_BODY" == "true" || "$STAGE5_FREEZE_ENCODER_BODY" == "yes" ]]; then
  extra_args+=(--stage5-freeze-encoder-body)
fi
if [[ "$STAGE5_TRAIN_PREFIX_HEAD_ONLY" == "1" || "$STAGE5_TRAIN_PREFIX_HEAD_ONLY" == "true" || "$STAGE5_TRAIN_PREFIX_HEAD_ONLY" == "yes" ]]; then
  extra_args+=(--stage5-train-prefix-head-only)
fi
if [[ "$STAGE5_TRAIN_CVQ" == "1" || "$STAGE5_TRAIN_CVQ" == "true" || "$STAGE5_TRAIN_CVQ" == "yes" ]]; then
  extra_args+=(--stage5-train-cvq)
fi

$PY MY/train_cvq/main.py \
  --stage 5 \
  --epochs "$STAGE5_EPOCHS" \
  --data-dir "$DATA_DIR" \
  --save-dir "$SAVE_DIR" \
  --init-ckpt "$INIT_CKPT" \
  "${extra_args[@]}" \
  --snr-db 9 \
  --latent-ch 36 \
  --prefix-ch 16 \
  --latent-h 16 \
  --latent-w 16 \
  --cvq-mode fsq \
  --k-a "$K_A" \
  --k-b "$K_B" \
  --fsq-levels-a "$FSQ_LEVELS_A" \
  --fsq-levels-b "$FSQ_LEVELS_B" \
  --car-arch factorized_swin \
  --car-dim "$CAR_DIM" \
  --car-heads "$CAR_HEADS" \
  --car-layers "$CAR_LAYERS" \
  --car-dropout "$CAR_DROPOUT" \
  --car-window-size "$CAR_WINDOW_SIZE" \
  --lr "$LR" \
  --car-lr "$CAR_LR" \
  --decoder-lr "$DECODER_LR" \
  --lambda-stage5-rec "$LAMBDA_STAGE5_REC" \
  --lambda-stage5-prefix "$LAMBDA_STAGE5_PREFIX" \
  --lambda-stage5-gain-margin "$LAMBDA_STAGE5_GAIN_MARGIN" \
  --stage5-gain-margin-db "$STAGE5_GAIN_MARGIN_DB" \
  --lambda-stage5-value "$LAMBDA_STAGE5_VALUE" \
  --lambda-stage5-ordinal "$LAMBDA_STAGE5_ORDINAL" \
  --lambda-stage5-vq "$LAMBDA_STAGE5_VQ" \
  --stage5-cvq-lr "$STAGE5_CVQ_LR" \
  --stage5-soft-tau "$STAGE5_SOFT_TAU" \
  --stage5-fsq-generate "$STAGE5_FSQ_GENERATE" \
  --stage5-min-tail-gain-car "$STAGE5_MIN_TAIL_GAIN_CAR" \
  --stage5-fsq-strategy "$STAGE5_FSQ_STRATEGY" \
  --stage5-two-stage-a-epochs "$STAGE5_TWO_STAGE_A_EPOCHS" \
  --stage5-gate-threshold "$STAGE5_GATE_THRESHOLD" \
  --stage5-gate-b-threshold "$STAGE5_GATE_B_THRESHOLD" \
  --stage5-gate-soft-temp "$STAGE5_GATE_SOFT_TEMP" \
  --stage5-gate-sweep="$STAGE5_GATE_SWEEP" \
  --stage5-tail-scale="$STAGE5_TAIL_SCALE" \
  --stage5-alpha-sweep="$STAGE5_ALPHA_SWEEP" \
  --stage5-mc-samples "$STAGE5_MC_SAMPLES" \
  --stage5-maskgit-iters "$STAGE5_MASKGIT_ITERS" \
  --stage5-maskgit-mask-prob "$STAGE5_MASKGIT_MASK_PROB" \
  --stage5-fsq-coarse-levels "$STAGE5_FSQ_COARSE_LEVELS" \
  --lambda-stage5-residual "$LAMBDA_STAGE5_RESIDUAL" \
  --lambda-stage5-gate-l1 "$LAMBDA_STAGE5_GATE_L1" \
  --stage5-residual-threshold "$STAGE5_RESIDUAL_THRESHOLD" \
  --batch-size "$BATCH_SIZE" \
  --test-batch "$TEST_BATCH" \
  --num-workers "$NUM_WORKERS" \
  --val-num-workers "$VAL_NUM_WORKERS" \
  --val-every "$VAL_EVERY" \
  --latest-every "$LATEST_EVERY" \
  --seed "$SEED" \
  2>&1 | tee "$SAVE_DIR/launch.console.log"
